name: carp_cli
description: Carp CLI allows developers to create and consume reusable templates.
version: 1.0.0
homepage: https://github.com/chihao10711/carp_cli.git

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  args: ^2.3.1
  mason: ^0.1.0-dev.31
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
